package edu.femxa.baseDatos.ejercicios;

public class Consultas {

	
	
	public static final String CONSULTA_EMPLEADOS_SALARIO_ASC ="SELECT E.FIRST_NAME, E.EMPLOYEE_ID, E.SALARY, E.DEPARTMENT_ID, D.DEPARTMENT_NAME from EMPLOYEES E, DEPARTMENTS D where E.DEPARTMENT_ID = D.DEPARTMENT_ID ORDER BY E.SALARY DESC";
	public static final String CONSULTA_HISTORICO ="SELECT SALARIO_ID, SALARIO_ANTERIOR, SALARIO_POSTERIOR, FECHA_SUBIDA, EMPLOYEE_ID from SUBIDA_SALARIO where TO_DATE (FECHA_SUBIDA, 'DD/MM/YYYY') = TO_DATE (sysdate, 'DD/MM/YYYY')";
	public static final String CONSULTA_SUBIDA_PORCENT ="UPDATE EMPLOYEES SALARY SET SALARY=round(SALARY*0.20+ SALARY,2) WHERE JOB_ID like 'AD%'";
	public static final String CONSULTA_SELECT_EMPLEADOS ="select * from EMPLOYEES where JOB_ID like 'AD%'";
	
}
